# LLM配置
llm:
  aliyun:
    api_key: sk-fa5986a1422c491fbeae3cdf2768811b
    api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
    model_name: deepseek-v3
    temperature: 1
    max_tokens: 4096
  siliconflow:
    api_key: sk-rijqlrrzmnwnfhyahoenktuwcpsspclohjvkifdeaobsmgvq
    api_base: https://api.siliconflow.cn/v1
    model_name: deepseek-ai/DeepSeek-V2.5
    temperature: 1
    max_tokens: 4096


# 日志配置
logging:
  level: INFO  # 日志级别：DEBUG, INFO, WARNING, ERROR, CRITICAL
  filename: langchain_demo.log  # 日志文件名
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式
  max_bytes: 1048576  # 单个日志文件最大大小（1MB）
  backup_count: 5  # 备份文件数量
  console_output: true  # 是否输出到控制台

miit:
  base_url: "https://www.miit.gov.cn/search/zcwjk.html"
  params:
    websiteid: "110000000000000"
    category: "183"
    tpl: "14"
  keywords: "绿色制造"
