server:
  port: 8765
spring:
  application:
    name: config-server
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpadeSeven/spade-demo-project
          searchPaths: java-project/spring-cloud/config-server/data
          username: SpadeSeven
          password: Zhang131023
      label: master
