server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SpadeSeven/spade-demo-project
          searchPaths: respo
          username:
          password:
      label: master
