spring:
  cloud:
    client:
      ipAddress: 192.168.0.106
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.168.10.27:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.106
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
