eureka:
  instance:
    hostname: 172.168.10.27
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/,http://172.168.10.22:${server.port}/eureka/
  server:
    enableSelfPreservation: true
spring:
  application:
    name: eurka-server
  cloud:
    client:
      ipAddress: 172.168.10.27
