eureka:
  instance:
    hostname: localhost
    easeRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server
