server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.168.10.27:8761/eureka/
spring:
  application:
    name: service-client
  profiles:
    active: dev
logging:
  level:
    com.netflix: DEBUG
