spring:
  cloud:
    client:
      ipAddress: 172.168.10.27
eureka:
  instance:
    hostname: 172.168.10.27
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      circuitBreaker:
        requestVolumeThreshold: 1000
        errorThresholdPercentage: 1000
        sleepWindowInMilliseconds: 100000
ribbon:
  eureka:
    enable: true
  ConnectTimeout: 1000
  ReadTimeout: 1000
SERVICE-HI:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
