server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.168.10.27:8761/eureka/
spring:
  application:
    name: service-client
  profiles:
    active: dev
  zipkin:
    base-url: http://172.168.10.22:9411
logging:
  level:
    com.netflix: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
